package struct;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
/**
 * JNA Wrapper for library <b>BITMAP_UPDATE</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class BITMAP_UPDATE_LIBRARY implements Library {

    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    /** Pointer to unknown (opaque) type */
    public static class BITMAP_DATA extends PointerType {
        public BITMAP_DATA(Pointer address) {
            super(address);
        }
        public BITMAP_DATA() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class UINT32 extends PointerType {
        public UINT32(Pointer address) {
            super(address);
        }
        public UINT32() {
            super();
        }
    };
}
