package struct;

import com.sun.jna.Structure;
import struct.BITMAP_UPDATE_LIBRARY.BITMAP_DATA;
import struct.BITMAP_UPDATE_LIBRARY.UINT32;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */

@com.sun.jna.Structure.FieldOrder({"number", "rectangles", "skipCompression"})
public class BITMAP_UPDATE extends Structure {
    public UINT32 number;
    public BITMAP_DATA rectangles;
    public boolean skipCompression;
    public BITMAP_UPDATE() {
        super();
    }

    public BITMAP_UPDATE(UINT32 number, BITMAP_DATA rectangles, boolean skipCompression) {
        super();
        this.number = number;
        this.rectangles = rectangles;
        this.skipCompression = skipCompression;
    }
    protected ByReference newByReference() { return new ByReference(); }
    protected ByValue newByValue() { return new ByValue(); }
    protected BITMAP_UPDATE newInstance() { return new BITMAP_UPDATE(); }

    public static class ByReference extends BITMAP_UPDATE implements Structure.ByReference {

    };
    public static class ByValue extends BITMAP_UPDATE implements Structure.ByValue {

    };
}
