package struct;
import com.ochafik.lang.jnaerator.runtime.LibraryExtractor;
import com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
/**
 * JNA Wrapper for library <b>rdpSettings</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class entryPoint_library implements Library {

    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    /** Pointer to unknown (opaque) type */
    public static class pRdpGlobalInit extends PointerType {
        public pRdpGlobalInit(Pointer address) {
            super(address);
        }
        public pRdpGlobalInit() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRdpClientFree extends PointerType {
        public pRdpClientFree(Pointer address) {
            super(address);
        }
        public pRdpClientFree() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRdpClientStop extends PointerType {
        public pRdpClientStop(Pointer address) {
            super(address);
        }
        public pRdpClientStop() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRdpClientNew extends PointerType {
        public pRdpClientNew(Pointer address) {
            super(address);
        }
        public pRdpClientNew() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpSettings extends PointerType {
        public rdpSettings(Pointer address) {
            super(address);
        }
        public rdpSettings() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRdpGlobalUninit extends PointerType {
        public pRdpGlobalUninit(Pointer address) {
            super(address);
        }
        public pRdpGlobalUninit() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRdpClientStart extends PointerType {
        public pRdpClientStart(Pointer address) {
            super(address);
        }
        public pRdpClientStart() {
            super();
        }
    };
}
