package struct;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;

/**
 * JNA Wrapper for library <b>rdp_context</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class rdp_context_library implements Library {
    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    /** Pointer to unknown (opaque) type */
    public static class rdpInput extends PointerType {
        public rdpInput(Pointer address) {
            super(address);
        }
        public rdpInput() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpMetrics extends PointerType {
        public rdpMetrics(Pointer address) {
            super(address);
        }
        public rdpMetrics() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpUpdate extends PointerType {
        public rdpUpdate(Pointer address) {
            super(address);
        }
        public rdpUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpRail extends PointerType {
        public rdpRail(Pointer address) {
            super(address);
        }
        public rdpRail() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class freerdp extends PointerType {
        public freerdp(Pointer address) {
            super(address);
        }
        public freerdp() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpGdi extends PointerType {
        public rdpGdi(Pointer address) {
            super(address);
        }
        public rdpGdi() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpCodecs extends PointerType {
        public rdpCodecs(Pointer address) {
            super(address);
        }
        public rdpCodecs() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpAutoDetect extends PointerType {
        public rdpAutoDetect(Pointer address) {
            super(address);
        }
        public rdpAutoDetect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class freerdp_peer extends PointerType {
        public freerdp_peer(Pointer address) {
            super(address);
        }
        public freerdp_peer() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpSettings extends PointerType {
        public rdpSettings(Pointer address) {
            super(address);
        }
        public rdpSettings() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpCache extends PointerType {
        public rdpCache(Pointer address) {
            super(address);
        }
        public rdpCache() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpChannels extends PointerType {
        public rdpChannels(Pointer address) {
            super(address);
        }
        public rdpChannels() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpGraphics extends PointerType {
        public rdpGraphics(Pointer address) {
            super(address);
        }
        public rdpGraphics() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class wPubSub extends PointerType {
        public wPubSub(Pointer address) {
            super(address);
        }
        public wPubSub() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class HANDLE extends PointerType {
        public HANDLE(Pointer address) {
            super(address);
        }
        public HANDLE() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpRdp extends PointerType {
        public rdpRdp(Pointer address) {
            super(address);
        }
        public rdpRdp() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpStreamDumpContext extends PointerType {
        public rdpStreamDumpContext(Pointer address) {
            super(address);
        }
        public rdpStreamDumpContext() {
            super();
        }
    };
}
