package struct;

import com.sun.jna.Structure;
import struct.rdp_update_library.*;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@com.sun.jna.Structure.FieldOrder({"context", "paddingA", "BeginPaint", "EndPaint", "SetBounds", "Synchronize", "DesktopResize", "BitmapUpdate", "Palette", "PlaySound", "SetKeyboardIndicators", "SetKeyboardImeStatus", "paddingB", "pointer", "primary", "secondary", "altsec", "window", "paddingC", "RefreshRect", "SuppressOutput", "RemoteMonitors", "paddingD", "SurfaceCommand", "SurfaceBits", "SurfaceFrameMarker", "SurfaceFrameBits", "SurfaceFrameAcknowledge", "SaveSessionInfo", "ServerStatusInfo", "autoCalculateBitmapData", "paddingE"})
public class rdp_update extends Structure {
    /** 0 */
    public rdpContext context;
    /** 1 */
    public UINT32[] paddingA = new UINT32[16 - 1];
    /** 16 */
    public pBeginPaint BeginPaint;
    /** 17 */
    public pEndPaint EndPaint;
    /** 18 */
    public pSetBounds SetBounds;
    /** 19 */
    public pSynchronize Synchronize;
    /** 20 */
    public pDesktopResize DesktopResize;
    /** 21 */
    public pBitmapUpdate BitmapUpdate;
    /** 22 */
    public pPalette Palette;
    /** 23 */
    public pPlaySound PlaySound;
    /** 24 */
    public pSetKeyboardIndicators SetKeyboardIndicators;
    /** 25 */
    public pSetKeyboardImeStatus SetKeyboardImeStatus;
    /** 26 */
    public UINT32[] paddingB = new UINT32[32 - 26];
    /** 32 */
    public rdpPointerUpdate pointer;
    /** 33 */
    public rdpPrimaryUpdate primary;
    /** 34 */
    public rdpSecondaryUpdate secondary;
    /** 35 */
    public rdpAltSecUpdate altsec;
    /** 36 */
    public rdpWindowUpdate window;
    /** 37 */
    public UINT32[] paddingC = new UINT32[48 - 37];
    /** 48 */
    public pRefreshRect RefreshRect;
    /** 49 */
    public pSuppressOutput SuppressOutput;
    /** 50 */
    public pRemoteMonitors RemoteMonitors;
    /** 51 */
    public UINT32[] paddingD = new UINT32[64 - 51];
    /** 64 */
    public pSurfaceCommand SurfaceCommand;
    /** 65 */
    public pSurfaceBits SurfaceBits;
    /** 66 */
    public pSurfaceFrameMarker SurfaceFrameMarker;
    /** 67 */
    public pSurfaceFrameBits SurfaceFrameBits;
    /** 68 */
    public pSurfaceFrameAcknowledge SurfaceFrameAcknowledge;
    /** 69 */
    public pSaveSessionInfo SaveSessionInfo;
    /** 70 */
    public pServerStatusInfo ServerStatusInfo;
    /**
     * if autoCalculateBitmapData is set to TRUE, the server automatically<br>
     * fills BITMAP_DATA struct members: flags, cbCompMainBodySize and cbCompFirstRowSize.<br>
     * 71
     */
    public boolean autoCalculateBitmapData;
    /** 72 */
    public UINT32[] paddingE = new UINT32[80 - 72];
    public rdp_update() {
        super();
    }
    protected ByReference newByReference() { return new ByReference(); }
    protected ByValue newByValue() { return new ByValue(); }
    protected rdp_update newInstance() { return new rdp_update(); }

    public static class ByReference extends rdp_update implements Structure.ByReference {

    };
    public static class ByValue extends rdp_update implements Structure.ByValue {

    };
}

