package struct;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;

/**
 * JNA Wrapper for library <b>rdp_freerdp</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class rdp_freerdp_library implements Library {

    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    /** Pointer to unknown (opaque) type */
    public static class rdpInput extends PointerType {
        public rdpInput(Pointer address) {
            super(address);
        }
        public rdpInput() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpHeartbeat extends PointerType {
        public rdpHeartbeat(Pointer address) {
            super(address);
        }
        public rdpHeartbeat() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPostConnect extends PointerType {
        public pPostConnect(Pointer address) {
            super(address);
        }
        public pPostConnect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSendChannelPacket extends PointerType {
        public pSendChannelPacket(Pointer address) {
            super(address);
        }
        public pSendChannelPacket() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pVerifyCertificateEx extends PointerType {
        public pVerifyCertificateEx(Pointer address) {
            super(address);
        }
        public pVerifyCertificateEx() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpUpdate extends PointerType {
        public rdpUpdate(Pointer address) {
            super(address);
        }
        public rdpUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPreConnect extends PointerType {
        public pPreConnect(Pointer address) {
            super(address);
        }
        public pPreConnect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pLogonErrorInfo extends PointerType {
        public pLogonErrorInfo(Pointer address) {
            super(address);
        }
        public pLogonErrorInfo() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPresentGatewayMessage extends PointerType {
        public pPresentGatewayMessage(Pointer address) {
            super(address);
        }
        public pPresentGatewayMessage() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSendChannelData extends PointerType {
        public pSendChannelData(Pointer address) {
            super(address);
        }
        public pSendChannelData() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRedirect extends PointerType {
        public pRedirect(Pointer address) {
            super(address);
        }
        public pRedirect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pVerifyChangedCertificateEx extends PointerType {
        public pVerifyChangedCertificateEx(Pointer address) {
            super(address);
        }
        public pVerifyChangedCertificateEx() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pContextNew extends PointerType {
        public pContextNew(Pointer address) {
            super(address);
        }
        public pContextNew() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pContextFree extends PointerType {
        public pContextFree(Pointer address) {
            super(address);
        }
        public pContextFree() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pAuthenticate extends PointerType {
        public pAuthenticate(Pointer address) {
            super(address);
        }
        public pAuthenticate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpContext extends PointerType {
        public rdpContext(Pointer address) {
            super(address);
        }
        public rdpContext() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpAutoDetect extends PointerType {
        public rdpAutoDetect(Pointer address) {
            super(address);
        }
        public rdpAutoDetect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpSettings extends PointerType {
        public rdpSettings(Pointer address) {
            super(address);
        }
        public rdpSettings() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pReceiveChannelData extends PointerType {
        public pReceiveChannelData(Pointer address) {
            super(address);
        }
        public pReceiveChannelData() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pAuthenticateEx extends PointerType {
        public pAuthenticateEx(Pointer address) {
            super(address);
        }
        public pAuthenticateEx() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPostDisconnect extends PointerType {
        public pPostDisconnect(Pointer address) {
            super(address);
        }
        public pPostDisconnect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pVerifyX509Certificate extends PointerType {
        public pVerifyX509Certificate(Pointer address) {
            super(address);
        }
        public pVerifyX509Certificate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class RDP_CLIENT_ENTRY_POINTS extends PointerType {
        public RDP_CLIENT_ENTRY_POINTS(Pointer address) {
            super(address);
        }
        public RDP_CLIENT_ENTRY_POINTS() {
            super();
        }
    };
}
