package struct;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
/**
 * JNA Wrapper for library <b>rdp_update</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class rdp_update_library implements Library {

    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    /** Pointer to unknown (opaque) type */
    public static class pRemoteMonitors extends PointerType {
        public pRemoteMonitors(Pointer address) {
            super(address);
        }
        public pRemoteMonitors() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpPointerUpdate extends PointerType {
        public rdpPointerUpdate(Pointer address) {
            super(address);
        }
        public rdpPointerUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSurfaceFrameBits extends PointerType {
        public pSurfaceFrameBits(Pointer address) {
            super(address);
        }
        public pSurfaceFrameBits() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSetBounds extends PointerType {
        public pSetBounds(Pointer address) {
            super(address);
        }
        public pSetBounds() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pBeginPaint extends PointerType {
        public pBeginPaint(Pointer address) {
            super(address);
        }
        public pBeginPaint() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pDesktopResize extends PointerType {
        public pDesktopResize(Pointer address) {
            super(address);
        }
        public pDesktopResize() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class UINT32 extends PointerType {
        public UINT32(Pointer address) {
            super(address);
        }
        public UINT32() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSetKeyboardImeStatus extends PointerType {
        public pSetKeyboardImeStatus(Pointer address) {
            super(address);
        }
        public pSetKeyboardImeStatus() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSaveSessionInfo extends PointerType {
        public pSaveSessionInfo(Pointer address) {
            super(address);
        }
        public pSaveSessionInfo() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpAltSecUpdate extends PointerType {
        public rdpAltSecUpdate(Pointer address) {
            super(address);
        }
        public rdpAltSecUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSurfaceFrameMarker extends PointerType {
        public pSurfaceFrameMarker(Pointer address) {
            super(address);
        }
        public pSurfaceFrameMarker() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPlaySound extends PointerType {
        public pPlaySound(Pointer address) {
            super(address);
        }
        public pPlaySound() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpWindowUpdate extends PointerType {
        public rdpWindowUpdate(Pointer address) {
            super(address);
        }
        public rdpWindowUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pEndPaint extends PointerType {
        public pEndPaint(Pointer address) {
            super(address);
        }
        public pEndPaint() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pBitmapUpdate extends PointerType {
        public pBitmapUpdate(Pointer address) {
            super(address);
        }
        public pBitmapUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpSecondaryUpdate extends PointerType {
        public rdpSecondaryUpdate(Pointer address) {
            super(address);
        }
        public rdpSecondaryUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSetKeyboardIndicators extends PointerType {
        public pSetKeyboardIndicators(Pointer address) {
            super(address);
        }
        public pSetKeyboardIndicators() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSuppressOutput extends PointerType {
        public pSuppressOutput(Pointer address) {
            super(address);
        }
        public pSuppressOutput() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pServerStatusInfo extends PointerType {
        public pServerStatusInfo(Pointer address) {
            super(address);
        }
        public pServerStatusInfo() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSurfaceCommand extends PointerType {
        public pSurfaceCommand(Pointer address) {
            super(address);
        }
        public pSurfaceCommand() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpPrimaryUpdate extends PointerType {
        public rdpPrimaryUpdate(Pointer address) {
            super(address);
        }
        public rdpPrimaryUpdate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSynchronize extends PointerType {
        public pSynchronize(Pointer address) {
            super(address);
        }
        public pSynchronize() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpContext extends PointerType {
        public rdpContext(Pointer address) {
            super(address);
        }
        public rdpContext() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pPalette extends PointerType {
        public pPalette(Pointer address) {
            super(address);
        }
        public pPalette() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSurfaceBits extends PointerType {
        public pSurfaceBits(Pointer address) {
            super(address);
        }
        public pSurfaceBits() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pRefreshRect extends PointerType {
        public pRefreshRect(Pointer address) {
            super(address);
        }
        public pRefreshRect() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class pSurfaceFrameAcknowledge extends PointerType {
        public pSurfaceFrameAcknowledge(Pointer address) {
            super(address);
        }
        public pSurfaceFrameAcknowledge() {
            super();
        }
    };
}

