package struct;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
/**
 * JNA Wrapper for library <b>rdpSettings</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class rdpSettings_library implements Library {

    static {
        Native.register("/Users/kimfk567/Documents/IntelliSave/FreeRDP-Mac2/client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP");
    }
    public static interface RDP_VERSION {
        public static final int RDP_VERSION_4 = 0x00080001;
        public static final int RDP_VERSION_5_PLUS = 0x00080004;
        public static final int RDP_VERSION_10_0 = 0x00080005;
        public static final int RDP_VERSION_10_1 = 0x00080006;
        public static final int RDP_VERSION_10_2 = 0x00080007;
        public static final int RDP_VERSION_10_3 = 0x00080008;
        public static final int RDP_VERSION_10_4 = 0x00080009;
        public static final int RDP_VERSION_10_5 = 0x0008000a;
        public static final int RDP_VERSION_10_6 = 0x0008000b;
        public static final int RDP_VERSION_10_7 = 0x0008000C;
    };
    public static final int FreeRDP_RemoteAssistanceRequestControl = (int)(1032);
    public static final int FreeRDP_DynamicResolutionUpdate = (int)(1558);
    public static final int FreeRDP_PasswordHash = (int)(24);
    public static final int FreeRDP_RemoteWndSupportLevel = (int)(2125);
    public static final int FreeRDP_DisableCtrlAltDel = (int)(706);
    public static final int FreeRDP_OsMinorType = (int)(2305);
    public static final int RNS_UD_CS_SUPPORT_DYNAMIC_TIME_ZONE = (int)0x0200;
    public static final int FreeRDP_DesktopPhysicalHeight = (int)(146);
    public static final int STATUS_VM_LOADING = (int)0x00000501;
    public static final int FreeRDP_ClientTimeZone = (int)(896);
    public static final int FreeRDP_SupportAsymetricKeys = (int)(138);
    public static final int FreeRDP_RedirectionTsvUrlLength = (int)(1227);
    public static final int FreeRDP_CertificateFile = (int)(1410);
    public static final int FreeRDP_RemoteApplicationExpandCmdLine = (int)(2119);
    public static final int FreeRDP_DesktopHeight = (int)(130);
    public static final int CHANNEL_OPTION_COMPRESS_RDP = (int)0x00800000;
    public static final int FreeRDP_RedirectionFlags = (int)(1216);
    public static final int NEG_OPAQUE_RECT_INDEX = (int)0x0A;
    public static final int FreeRDP_ClientRandom = (int)(200);
    public static final int FreeRDP_ClientRandomLength = (int)(201);
    public static final int FreeRDP_SendPreconnectionPdu = (int)(1156);
    public static final int NEG_SCRBLT_INDEX = (int)0x02;
    public static final int NEG_SAVEBITMAP_INDEX = (int)0x0B;
    public static final int CHANNEL_OPTION_INITIALIZED = (int)0x80000000;
    public static final int TSC_PROXY_MODE_DIRECT = (int)0x1;
    public static final int LB_PASSWORD = (int)0x00000010;
    public static final int NEG_AEXTTEXTOUT_INDEX = (int)0x06;
    public static final int FreeRDP_RedirectionAcceptedCertLength = (int)(1232);
    public static final int FreeRDP_ServerCertificate = (int)(198);
    public static final int FreeRDP_MonitorIds = (int)(393);
    public static final int FreeRDP_RemoteConsoleAudio = (int)(713);
    public static final int FreeRDP_UsingSavedCredentials = (int)(718);
    public static final int FreeRDP_ToggleFullscreen = (int)(1548);
    public static final int FreeRDP_RemoteApplicationSupportMask = (int)(2127);
    public static final int ORIENTATION_LANDSCAPE = (int)0;
    public static final int CS_MULTITRANSPORT = (int)0xC00A;
    public static final int FreeRDP_RemoteApplicationCmdLine = (int)(2118);
    public static final int NEG_WTEXTOUT_INDEX = (int)0x0C;
    public static final int FreeRDP_TransportDump = (int)(1860);
    public static final int FreeRDP_SoundBeepsEnabled = (int)(2944);
    public static final int FreeRDP_RemoteFxCaptureFlags = (int)(3653);
    public static final int RNS_UD_COLOR_8BPP = (int)0xCA01;
    public static final int FreeRDP_ShellWorkingDirectory = (int)(641);
    public static final int FreeRDP_OldLicenseBehaviour = (int)(1606);
    public static final int FreeRDP_TlsSecLevel = (int)(1105);
    public static final int RAIL_LEVEL_DOCKED_LANGBAR_SUPPORTED = (int)0x00000002;
    public static final int FreeRDP_ExtSecurity = (int)(1091);
    public static final int LOGON_FAILED_OTHER = (int)0x00000002;
    public static final int RNS_UD_CS_SUPPORT_DYNVC_GFX_PROTOCOL = (int)0x0100;
    public static final int ENCRYPTION_METHOD_40BIT = (int)0x00000001;
    public static final int NEG_DRAWNINEGRID_INDEX = (int)0x07;
    public static final int FreeRDP_KerberosStartTime = (int)(1346);
    public static final int FreeRDP_DisableCursorShadow = (int)(966);
    public static final int FreeRDP_PointerCacheSize = (int)(2561);
    public static final int FreeRDP_GatewayHttpUseWebsockets = (int)(2000);
    public static final int FreeRDP_ServerHostname = (int)(20);
    public static final int FreeRDP_ServerMode = (int)(16);
    public static final int FreeRDP_ListMonitors = (int)(392);
    public static final int FreeRDP_AllowFontSmoothing = (int)(961);
    public static final int FreeRDP_LoadBalanceInfo = (int)(1218);
    public static final int FreeRDP_RestrictedAdminModeRequired = (int)(1097);
    public static final int FreeRDP_DrawNineGridCacheEntries = (int)(3970);
    public static final int RNS_UD_CS_SUPPORT_HEARTBEAT_PDU = (int)0x0400;
    public static final int FreeRDP_DrawNineGridEnabled = (int)(3968);
    public static final int LB_NOREDIRECT = (int)0x00000080;
    public static final int FreeRDP_RdpVersion = (int)(128);
    public static final int FreeRDP_ParentWindowId = (int)(1543);
    public static final int STATUS_REDIRECTING_TO_DESTINATION = (int)0x00000404;
    public static final int FreeRDP_KerberosRenewableLifeTime = (int)(1348);
    public static final int FreeRDP_RemoteApplicationIcon = (int)(2114);
    public static final int FreeRDP_PlayRemoteFxFile = (int)(1859);
    public static final int NEG_GLYPH_WEXTTEXTOUT_INDEX = (int)0x1C;
    public static final int FreeRDP_SupportHeartbeatPdu = (int)(144);
    public static final int FreeRDP_NtlmSamFile = (int)(1103);
    public static final int FreeRDP_SmartcardEmulation = (int)(1288);
    public static final int GLYPH_SUPPORT_PARTIAL = (int)0x0001;
    public static final int FreeRDP_DynamicDaylightTimeDisabled = (int)(898);
    public static final int FreeRDP_GfxAVC444 = (int)(3845);
    public static final int FreeRDP_SupportMonitorLayoutPdu = (int)(141);
    public static final int FreeRDP_MaxTimeInCheckLoop = (int)(26);
    public static final int FreeRDP_CspName = (int)(1295);
    public static final int CHANNEL_OPTION_ENCRYPT_CS = (int)0x10000000;
    public static final int TRANSPORT_TYPE_UDP_PREFERRED = (int)0x00000100;
    public static final int FreeRDP_Decorations = (int)(1540);
    public static final int FreeRDP_ProxyType = (int)(2015);
    public static final int PACKET_COMPR_TYPE_RDP6 = (int)0x02;
    public static final int FreeRDP_KeyboardLayout = (int)(2624);
    public static final int FreeRDP_LoadBalanceInfoLength = (int)(1219);
    public static final int FreeRDP_ServerCertificateLength = (int)(199);
    public static final int PACKET_COMPR_TYPE_RDP8 = (int)0x04;
    public static final int FreeRDP_RemoteFxCodec = (int)(3649);
    public static final int FreeRDP_RedirectionDomain = (int)(1221);
    public static final int FreeRDP_WaitForOutputBufferFlush = (int)(25);
    public static final int FreeRDP_SelectedProtocol = (int)(1094);
    public static final int SC_MULTITRANSPORT = (int)0x0C08;
    public static final int FreeRDP_Fullscreen = (int)(1537);
    public static final int FreeRDP_NumMonitorIds = (int)(394);
    public static final int FreeRDP_AudioCapture = (int)(715);
    public static final int FreeRDP_GatewayUdpTransport = (int)(1996);
    public static final int FreeRDP_RemoteFxOnly = (int)(3648);
    public static final int FreeRDP_AutoReconnectMaxRetries = (int)(833);
    public static final int FreeRDP_GfxSendQoeAck = (int)(3846);
    public static final int CHANNEL_REMOTE_CONTROL_PERSISTENT = (int)0x00100000;
    public static final int TSC_PROXY_CREDS_MODE_SMARTCARD = (int)0x1;
    public static final int FreeRDP_RdpServerCertificate = (int)(1414);
    public static final int LB_PASSWORD_MAX_LENGTH = (int)512;
    public static final int FreeRDP_EmbeddedWindow = (int)(1550);
    public static final int FreeRDP_FastPathInput = (int)(2630);
    public static final int FreeRDP_DrawGdiPlusEnabled = (int)(4032);
    public static final int FreeRDP_LogonNotify = (int)(709);
    public static final int FreeRDP_KerberosCache = (int)(1349);
    public static final int FreeRDP_RemoteFxCodecMode = (int)(3651);
    public static final int FreeRDP_PreconnectionBlob = (int)(1155);
    public static final int FreeRDP_Floatbar = (int)(5196);
    public static final int FreeRDP_SupportMultitransport = (int)(513);
    public static final int FreeRDP_MultitransportFlags = (int)(512);
    public static final int NEG_FAST_GLYPH_INDEX = (int)0x18;
    public static final int NEG_POLYGON_CB_INDEX = (int)0x15;
    public static final int FreeRDP_AutoReconnectionEnabled = (int)(832);
    public static final int FreeRDP_JpegCodec = (int)(3776);
    public static final int FreeRDP_SmartcardLogon = (int)(1282);
    public static final int FreeRDP_GrabKeyboard = (int)(1539);
    public static final int FreeRDP_DeviceArraySize = (int)(4162);
    public static final int FreeRDP_CertificateUseKnownHosts = (int)(1422);
    public static final int FreeRDP_HiDefRemoteApp = (int)(720);
    public static final int FreeRDP_GatewayAccessToken = (int)(1997);
    public static final int FreeRDP_DumpRemoteFxFile = (int)(1858);
    public static final int FreeRDP_PrivateKeyFile = (int)(1411);
    public static final int NEG_UNUSED31_INDEX = (int)0x1F;
    public static final int FreeRDP_DeviceArray = (int)(4163);
    public static final int FreeRDP_FrameAcknowledge = (int)(3714);
    public static final int FreeRDP_GfxAVC444v2 = (int)(3847);
    public static final int FreeRDP_ConfigPath = (int)(1793);
    public static final int PROXY_TYPE_IGNORE = (int)0xFFFF;
    public static final int FreeRDP_CertificateAcceptedFingerprints = (int)(1421);
    public static final int CHANNEL_OPTION_PRI_MED = (int)0x04000000;
    public static final int FreeRDP_SoftwareGdi = (int)(1601);
    public static final int FreeRDP_NlaSecurity = (int)(1089);
    public static final int CHANNEL_OPTION_ENCRYPT_RDP = (int)0x40000000;
    public static final int FreeRDP_ColorPointerFlag = (int)(2560);
    public static final int FreeRDP_EncomspVirtualChannel = (int)(1029);
    public static final int LB_CLIENT_TSV_URL = (int)0x00001000;
    public static final int FreeRDP_RdpKeyContent = (int)(1418);
    public static final int FreeRDP_SmartSizingWidth = (int)(1554);
    public static final int FreeRDP_TcpConnectTimeout = (int)(5197);
    public static final int FreeRDP_BitmapCacheVersion = (int)(2498);
    public static final int FreeRDP_EnableWindowsKey = (int)(707);
    public static final int FreeRDP_SupportEchoChannel = (int)(5184);
    public static final int CHANNEL_OPTION_PRI_HIGH = (int)0x08000000;
    public static final int AUDIO_MODE_PLAY_ON_SERVER = (int)1;
    public static final int FreeRDP_GatewayHostname = (int)(1986);
    public static final int FreeRDP_GatewayBypassLocal = (int)(1993);
    public static final int FreeRDP_UseRdpSecurityLayer = (int)(192);
    public static final int RNS_UD_CS_VALID_CONNECTION_TYPE = (int)0x0020;
    public static final int FreeRDP_RdpSecurity = (int)(1090);
    public static final int TSC_PROXY_MODE_DETECT = (int)0x2;
    public static final int FreeRDP_PkinitAnchors = (int)(1290);
    public static final int FreeRDP_PreconnectionId = (int)(1154);
    public static final int CS_CORE = (int)0xC001;
    public static final int FreeRDP_BitmapCompressionDisabled = (int)(2312);
    public static final int FreeRDP_RemdeskVirtualChannel = (int)(1030);
    public static final int FreeRDP_MouseHasWheel = (int)(712);
    public static final int THREADING_FLAGS_DISABLE_THREADS = (int)0x00000001;
    public static final int RNS_UD_CS_WANT_32BPP_SESSION = (int)0x0002;
    public static final int FreeRDP_RemoteApplicationProgram = (int)(2115);
    public static final int FreeRDP_RedirectClipboard = (int)(4800);
    public static final int RNS_UD_CS_SUPPORT_STATUSINFO_PDU = (int)0x0004;
    public static final int FreeRDP_ClusterInfoFlags = (int)(320);
    public static final int FreeRDP_OffscreenCacheSize = (int)(2817);
    public static final int FreeRDP_ColorDepth = (int)(131);
    public static final int FreeRDP_DesktopPhysicalWidth = (int)(145);
    public static final int PROXY_TYPE_SOCKS = (int)2;
    public static final int ORIENTATION_LANDSCAPE_FLIPPED = (int)180;
    public static final int FreeRDP_ServerPort = (int)(19);
    public static final int FreeRDP_AllowDesktopComposition = (int)(968);
    public static final int FreeRDP_GatewayAcceptedCertLength = (int)(1999);
    public static final int FreeRDP_RemoteAppNumIconCacheEntries = (int)(2123);
    public static final int FreeRDP_KeyboardType = (int)(2625);
    public static final int FreeRDP_GfxCapsFilter = (int)(3848);
    public static final int FreeRDP_EncryptionMethods = (int)(193);
    public static final int FreeRDP_PduSource = (int)(18);
    public static final int PERF_DISABLE_THEMING = (int)0x00000008;
    public static final int FreeRDP_OsMajorType = (int)(2304);
    public static final int FreeRDP_VirtualChannelChunkSize = (int)(2881);
    public static final int FreeRDP_DisableMenuAnims = (int)(964);
    public static final int NEG_ATEXTOUT_INDEX = (int)0x05;
    public static final int TSC_PROXY_MODE_NONE_DETECT = (int)0x4;
    public static final int FreeRDP_NSCodecAllowDynamicColorFidelity = (int)(3717);
    public static final int FreeRDP_SaltedChecksum = (int)(2309);
    public static final int FreeRDP_BitmapCacheV3Enabled = (int)(2433);
    public static final int RAIL_LEVEL_HIDE_MINIMIZED_APPS_SUPPORTED = (int)0x00000020;
    public static final int FreeRDP_RedirectionTargetFQDN = (int)(1224);
    public static final int FreeRDP_SmartSizingHeight = (int)(1555);
    public static final int FreeRDP_DisableCursorBlinking = (int)(967);
    public static final int FreeRDP_RemoteApplicationWorkingDir = (int)(2128);
    public static final int FreeRDP_SurfaceCommandsEnabled = (int)(3520);
    public static final int CONNECTION_TYPE_BROADBAND_HIGH = (int)0x04;
    public static final int RNS_UD_SC_EDGE_ACTIONS_SUPPORTED = (int)0x00000001;
    public static final int FreeRDP_ForceMultimon = (int)(389);
    public static final int STATUS_FINDING_DESTINATION = (int)0x00000401;
    public static final int FreeRDP_RemoteApplicationFile = (int)(2116);
    public static final int RAIL_LEVEL_SERVER_TO_CLIENT_IME_SYNC_SUPPORTED = (int)0x00000010;
    public static final int PERF_DISABLE_WALLPAPER = (int)0x00000001;
    public static final int FreeRDP_AllowedTlsCiphers = (int)(1101);
    public static final int RNS_UD_CS_STRONG_ASYMMETRIC_KEYS = (int)0x0008;
    public static final int FreeRDP_RedirectParallelPorts = (int)(4673);
    public static final int FreeRDP_GfxThinClient = (int)(3840);
    public static final int FreeRDP_ConnectionType = (int)(132);
    public static final int LOGON_MSG_SESSION_TERMINATE = (int)0xFFFFFFFD;
    public static final int NEG_MULTIPATBLT_INDEX = (int)0x10;
    public static final int FreeRDP_TcpKeepAliveInterval = (int)(5193);
    public static final int FreeRDP_Settings_StableAPI_MAX = (int)5312;
    public static final int DEFAULT_COOKIE_MAX_LENGTH = (int)0xFF;
    public static final int FreeRDP_TlsSecurity = (int)(1088);
    public static final int FreeRDP_CredentialsFromStdin = (int)(1604);
    public static final int FreeRDP_DynamicChannelArraySize = (int)(5057);
    public static final int TSC_PROXY_CREDS_MODE_ANY = (int)0x2;
    public static final int FreeRDP_DisableCredentialsDelegation = (int)(1099);
    public static final int RNS_UD_SC_DYNAMIC_DST_SUPPORTED = (int)0x00000002;
    public static final int FreeRDP_ChannelDefArray = (int)(258);
    public static final int FreeRDP_RemoteAssistanceMode = (int)(1024);
    public static final int FreeRDP_RedirectedSessionId = (int)(321);
    public static final int FreeRDP_RemoteApplicationSupportLevel = (int)(2126);
    public static final int FreeRDP_ShareId = (int)(17);
    public static final int FreeRDP_SupportSSHAgentChannel = (int)(5187);
    public static final int LOGON_MSG_RECONNECT_OPTIONS = (int)0xFFFFFFFC;
    public static final int STATUS_VM_BOOTING = (int)0x00000503;
    public static final int FreeRDP_RemoteApplicationMode = (int)(2112);
    public static final int FreeRDP_MultiTouchGestures = (int)(2632);
    public static final int FreeRDP_GatewayCredentialsSource = (int)(1990);
    public static final int FreeRDP_ChannelCount = (int)(256);
    public static final int FreeRDP_ComputerName = (int)(1664);
    public static final int SC_SECURITY = (int)0x0C02;
    public static final int FreeRDP_RemoteAssistancePassword = (int)(1027);
    public static final int CS_CLUSTER = (int)0xC004;
    public static final int PERF_ENABLE_DESKTOP_COMPOSITION = (int)0x00000100;
    public static final int FreeRDP_TargetNetAddress = (int)(1217);
    public static final int FreeRDP_ClientDir = (int)(770);
    public static final int FreeRDP_DrivesToRedirect = (int)(4290);
    public static final int FreeRDP_AuthenticationOnly = (int)(1603);
    public static final int REDIRECTED_SMARTCARD = (int)0x00000040;
    public static final int FreeRDP_SupportDynamicTimeZone = (int)(143);
    public static final int FreeRDP_CertificateCallbackPreferPEM = (int)(1423);
    public static final int FreeRDP_FrameMarkerCommandEnabled = (int)(3521);
    public static final int AUDIO_MODE_REDIRECT = (int)0;
    public static final int FreeRDP_CookieMaxLength = (int)(1153);
    public static final int KEYBOARD_HOOK_FULLSCREEN_ONLY = (int)2;
    public static final int FreeRDP_DeviceCount = (int)(4161);
    public static final int RAIL_LEVEL_HANDSHAKE_EX_SUPPORTED = (int)0x00000080;
    public static final int FreeRDP_JpegCodecId = (int)(3777);
    public static final int FreeRDP_RedirectSerialPorts = (int)(4672);
    public static final int FreeRDP_LogonErrors = (int)(710);
    public static final int GLYPH_SUPPORT_NONE = (int)0x0000;
    public static final int FreeRDP_AudioPlayback = (int)(714);
    public static final int FreeRDP_AuthenticationServiceClass = (int)(1098);
    public static final int FreeRDP_HasHorizontalWheel = (int)(2634);
    public static final int FreeRDP_DesktopPosX = (int)(390);
    public static final int FreeRDP_DesktopPosY = (int)(391);
    public static final int FreeRDP_GatewayDomain = (int)(1989);
    public static final int CONNECTION_TYPE_WAN = (int)0x05;
    public static final int NEG_MEMBLT_INDEX = (int)0x03;
    public static final int FreeRDP_JpegQuality = (int)(3778);
    public static final int CHANNEL_OPTION_COMPRESS = (int)0x00400000;
    public static final int PERF_DISABLE_CURSOR_SHADOW = (int)0x00000020;
    public static final int FreeRDP_LargePointerFlag = (int)(3392);
    public static final int FreeRDP_PercentScreenUseWidth = (int)(1556);
    public static final int LOGON_MSG_NO_PERMISSION = (int)0xFFFFFFFA;
    public static final int FreeRDP_ActionScript = (int)(5195);
    public static final int ENCRYPTION_METHOD_128BIT = (int)0x00000002;
    public static final int ENCRYPTION_LEVEL_HIGH = (int)0x00000003;
    public static final int FreeRDP_RedirectionTsvUrl = (int)(1226);
    public static final int FreeRDP_TargetNetPorts = (int)(1230);
    public static final int CONNECTION_TYPE_AUTODETECT = (int)0x07;
    public static final int REDIRECTION_SUPPORTED = (int)0x00000001;
    public static final int ENCRYPTION_METHOD_NONE = (int)0x00000000;
    public static final int NEG_MULTISCRBLT_INDEX = (int)0x11;
    public static final int FreeRDP_RemoteAssistanceSessionId = (int)(1025);
    public static final int LB_DOMAIN = (int)0x00000008;
    public static final int FreeRDP_IgnoreCertificate = (int)(1408);
    public static final int FreeRDP_GatewayPort = (int)(1985);
    public static final int RAIL_LEVEL_SHELL_INTEGRATION_SUPPORTED = (int)0x00000004;
    public static final int FreeRDP_CertificateContent = (int)(1416);
    public static final int TSC_PROXY_CREDS_MODE_USERPASS = (int)0x0;
    public static final int FreeRDP_CardName = (int)(1292);
    public static final int FreeRDP_CompressionEnabled = (int)(705);
    public static final int ENCRYPTION_LEVEL_FIPS = (int)0x00000004;
    public static final int FreeRDP_LongCredentialsSupported = (int)(2310);
    public static final int CS_MONITOR_EX = (int)0xC008;
    public static final int FreeRDP_KerberosArmor = (int)(1350);
    public static final int RNS_UD_COLOR_16BPP_565 = (int)0xCA03;
    public static final int FreeRDP_DesktopScaleFactor = (int)(148);
    public static final int TSC_PROXY_MODE_NONE_DIRECT = (int)0x0;
    public static final int RNS_UD_CS_SUPPORT_ERRINFO_PDU = (int)0x0001;
    public static final int ENCRYPTION_LEVEL_CLIENT_COMPATIBLE = (int)0x00000002;
    public static final int FreeRDP_AllowCacheWaitingList = (int)(2499);
    public static final int FreeRDP_PerformanceFlags = (int)(960);
    public static final int CS_MONITOR = (int)0xC005;
    public static final int LB_TARGET_NET_ADDRESSES = (int)0x00000800;
    public static final int FreeRDP_EncryptionLevel = (int)(195);
    public static final int FreeRDP_Password = (int)(22);
    public static final int FreeRDP_ClientProductId = (int)(135);
    public static final int FreeRDP_KeyboardRemappingList = (int)(2622);
    public static final int LB_SMARTCARD_LOGON = (int)0x00000040;
    public static final int FreeRDP_ProxyPort = (int)(2017);
    public static final int FreeRDP_FIPSMode = (int)(1104);
    public static final int FreeRDP_ClientAutoReconnectCookie = (int)(834);
    public static final int FreeRDP_GfxProgressiveV2 = (int)(3843);
    public static final int FreeRDP_MonitorDefArraySize = (int)(385);
    public static final int FreeRDP_RefreshRect = (int)(2306);
    public static final int ENCRYPTION_METHOD_56BIT = (int)0x00000008;
    public static final int RNS_UD_COLOR_16BPP_555 = (int)0xCA02;
    public static final int CS_NET = (int)0xC003;
    public static final int FreeRDP_MultifragMaxRequestSize = (int)(3328);
    public static final int CONNECTION_TYPE_BROADBAND_LOW = (int)0x02;
    public static final int FreeRDP_RemoteFxCodecId = (int)(3650);
    public static final int FreeRDP_DrawAllowDynamicColorFidelity = (int)(2369);
    public static final int FreeRDP_IPv6Enabled = (int)(768);
    public static final int FreeRDP_DrawNineGridCacheSize = (int)(3969);
    public static final int FreeRDP_DesktopOrientation = (int)(147);
    public static final int FreeRDP_UnicodeInput = (int)(2629);
    public static final int RNS_UD_24BPP_SUPPORT = (int)0x0001;
    public static final int FreeRDP_TcpKeepAlive = (int)(5190);
    public static final int FreeRDP_DisableWallpaper = (int)(962);
    public static final int LB_TARGET_NET_ADDRESS = (int)0x00000001;
    public static final int CONNECTION_TYPE_LAN = (int)0x06;
    public static final int FreeRDP_RemoteAppLanguageBarSupported = (int)(2124);
    public static final int FreeRDP_GfxSmallCache = (int)(3841);
    public static final int LOGON_FAILED_UPDATE_PASSWORD = (int)0x00000001;
    public static final int FreeRDP_ClientHostname = (int)(134);
    public static final int FreeRDP_ServerRandom = (int)(196);
    public static final int FreeRDP_MonitorDefArray = (int)(386);
    public static final int FreeRDP_SmartcardPrivateKey = (int)(1286);
    public static final int FreeRDP_BitmapCacheEnabled = (int)(2497);
    public static final int STATUS_BRINGING_SESSION_ONLINE = (int)0x00000403;
    public static final int FreeRDP_OrderSupport = (int)(2432);
    public static final int FreeRDP_GatewayHttpTransport = (int)(1995);
    public static final int NEG_GLYPH_INDEX_INDEX = (int)0x1B;
    public static final int FreeRDP_MaximizeShell = (int)(708);
    public static final int CS_SECURITY = (int)0xC002;
    public static final int RNS_UD_32BPP_SUPPORT = (int)0x0008;
    public static final int FreeRDP_GrabMouse = (int)(1559);
    public static final int SC_NET = (int)0x0C03;
    public static final int FreeRDP_AcceptedCertLength = (int)(28);
    public static final int FreeRDP_RequestedProtocols = (int)(1093);
    public static final int FreeRDP_AutoDenyCertificate = (int)(1420);
    public static final int FreeRDP_StaticChannelArraySize = (int)(4929);
    public static final int FreeRDP_ConsoleSession = (int)(322);
    public static final int FreeRDP_TransportDumpReplay = (int)(1862);
    public static final int NEG_FAST_INDEX_INDEX = (int)0x13;
    public static final int LB_USERNAME = (int)0x00000004;
    public static final int NEG_POLYLINE_INDEX = (int)0x16;
    public static final int SC_CORE = (int)0x0C01;
    public static final int FreeRDP_AutoLogonEnabled = (int)(704);
    public static final int FreeRDP_MouseAttached = (int)(711);
    public static final int FreeRDP_RemoteApplicationName = (int)(2113);
    public static final int GLYPH_SUPPORT_FULL = (int)0x0002;
    public static final int SC_MCS_MSGCHANNEL = (int)0x0C04;
    public static final int FreeRDP_ExtEncryptionMethods = (int)(194);
    public static final int CHANNEL_OPTION_PRI_LOW = (int)0x02000000;
    public static final int FreeRDP_SuspendInput = (int)(2636);
    public static final int FreeRDP_ChannelDefArraySize = (int)(257);
    public static final int FreeRDP_KerberosRealm = (int)(1345);
    public static final int ORIENTATION_PORTRAIT = (int)90;
    public static final int FreeRDP_RemoteApplicationGuid = (int)(2117);
    public static final int RNS_UD_CS_SUPPORT_NETCHAR_AUTODETECT = (int)0x0080;
    public static final int FreeRDP_OffscreenSupportLevel = (int)(2816);
    public static final int NEG_DSTBLT_INDEX = (int)0x00;
    public static final int FreeRDP_SupportErrorInfoPdu = (int)(139);
    public static final int STATUS_VM_WAKING = (int)0x00000502;
    public static final int FreeRDP_FastPathOutput = (int)(2308);
    public static final int FreeRDP_GlyphSupportLevel = (int)(2752);
    public static final int LOGON_MSG_SESSION_CONTINUE = (int)0xFFFFFFFE;
    public static final int FreeRDP_StaticChannelArray = (int)(4930);
    public static final int FreeRDP_TcpAckTimeout = (int)(5194);
    public static final int FreeRDP_VideoDisable = (int)(716);
    public static final int FreeRDP_GatewayUsername = (int)(1987);
    public static final int FreeRDP_WindowTitle = (int)(1542);
    public static final int FreeRDP_ProxyUsername = (int)(2018);
    public static final int FreeRDP_RemoteApplicationExpandWorkingDir = (int)(2120);
    public static final int FreeRDP_BrushSupportLevel = (int)(2688);
    public static final int FreeRDP_ServerAutoReconnectCookie = (int)(835);
    public static final int FreeRDP_RedirectionPreferType = (int)(1233);
    public static final int FreeRDP_LocalConnection = (int)(1602);
    public static final int FreeRDP_ClientAddress = (int)(769);
    public static final int FreeRDP_LyncRdpMode = (int)(1031);
    public static final int FreeRDP_DisableRemoteAppCapsCheck = (int)(2121);
    public static final int FreeRDP_VmConnectMode = (int)(1102);
    public static final int RAIL_LEVEL_WINDOW_CLOAKING_SUPPORTED = (int)0x00000040;
    public static final int NEG_MEM3BLT_INDEX = (int)0x04;
    public static final int NEG_MEMBLT_V2_INDEX = (int)0x0D;
    public static final int FreeRDP_DisableThemes = (int)(965);
    public static final int LOGON_MSG_DISCONNECT_REFUSED = (int)0xFFFFFFF9;
    public static final int FreeRDP_DesktopResize = (int)(2368);
    public static final int FreeRDP_ConnectionFile = (int)(1728);
    public static final int FreeRDP_RedirectionUsername = (int)(1220);
    public static final int LOGON_FAILED_BAD_PASSWORD = (int)0x00000000;
    public static final int FreeRDP_KeyboardFunctionKey = (int)(2627);
    public static final int FreeRDP_GfxPlanar = (int)(3849);
    public static final int PROXY_TYPE_NONE = (int)0;
    public static final int FreeRDP_AssistanceFile = (int)(1729);
    public static final int FreeRDP_SupportStatusInfoPdu = (int)(140);
    public static final int FreeRDP_YPan = (int)(1553);
    public static final int FreeRDP_PreferIPv6OverIPv4 = (int)(4674);
    public static final int FreeRDP_KerberosKdc = (int)(1344);
    public static final int CONNECTION_TYPE_SATELLITE = (int)0x03;
    public static final int FreeRDP_OffscreenCacheEntries = (int)(2818);
    public static final int RNS_UD_COLOR_4BPP = (int)0xCA00;
    public static final int ORIENTATION_PORTRAIT_FLIPPED = (int)270;
    public static final int FreeRDP_ProxyPassword = (int)(2019);
    public static final int FreeRDP_DynamicChannelCount = (int)(5056);
    public static final int PERF_DISABLE_CURSORSETTINGS = (int)0x00000040;
    public static final int FreeRDP_SmartcardCertificate = (int)(1285);
    public static final int FreeRDP_ContainerName = (int)(1294);
    public static final int FreeRDP_RedirectionPassword = (int)(1222);
    public static final int FreeRDP_SmartSizing = (int)(1551);
    public static final int FreeRDP_BitmapCacheV2CellInfo = (int)(2502);
    public static final int PACKET_COMPR_TYPE_RDP61 = (int)0x03;
    public static final int FreeRDP_MonitorLocalShiftY = (int)(396);
    public static final int FreeRDP_GatewayPassword = (int)(1988);
    public static final int FreeRDP_MonitorLocalShiftX = (int)(395);
    public static final int FreeRDP_NoBitmapCompressionHeader = (int)(2311);
    public static final int LB_DONTSTOREUSERNAME = (int)0x00000020;
    public static final int RAIL_LEVEL_SUPPORTED = (int)0x00000001;
    public static final int MSTSC_COOKIE_MAX_LENGTH = (int)9;
    public static final int FreeRDP_MouseMotion = (int)(1541);
    public static final int NEG_POLYGON_SC_INDEX = (int)0x14;
    public static final int FreeRDP_ThreadingFlags = (int)(64);
    public static final int FreeRDP_MultiTouchInput = (int)(2631);
    public static final int FreeRDP_GatewayRpcTransport = (int)(1994);
    public static final int FreeRDP_PlayRemoteFx = (int)(1857);
    public static final int FreeRDP_DeactivateClientDecoding = (int)(1863);
    public static final int FreeRDP_VirtualChannelCompressionFlags = (int)(2880);
    public static final int FreeRDP_KerberosLifeTime = (int)(1347);
    public static final int CHANNEL_OPTION_ENCRYPT_SC = (int)0x20000000;
    public static final int FreeRDP_AuthenticationLevel = (int)(1100);
    public static final int FreeRDP_NegotiateSecurityLayer = (int)(1096);
    public static final int FreeRDP_RedirectDrives = (int)(4288);
    public static final int PERF_DISABLE_FULLWINDOWDRAG = (int)0x00000002;
    public static final int NEG_GLYPH_WLONGTEXTOUT_INDEX = (int)0x1D;
    public static final int ENCRYPTION_METHOD_FIPS = (int)0x00000010;
    public static final int FreeRDP_ServerRandomLength = (int)(197);
    public static final int FreeRDP_CertificateName = (int)(1409);
    public static final int CONNECTION_TYPE_MODEM = (int)0x01;
    public static final int PACKET_COMPR_TYPE_8K = (int)0x00;
    public static final int FreeRDP_RDP2TCPArgs = (int)(5189);
    public static final int FreeRDP_TargetNetAddresses = (int)(1229);
    public static final int FreeRDP_TargetNetAddressCount = (int)(1228);
    public static final int FreeRDP_NSCodecId = (int)(3713);
    public static final int NEG_MEM3BLT_V2_INDEX = (int)0x0E;
    public static final int FreeRDP_SupportDynamicChannels = (int)(5059);
    public static final int FreeRDP_Password51 = (int)(1280);
    public static final int GLYPH_SUPPORT_ENCODE = (int)0x0003;
    public static final int FreeRDP_RedirectPrinters = (int)(4544);
    public static final int PROXY_TYPE_HTTP = (int)1;
    public static final int FreeRDP_RemoteAssistanceRCTicket = (int)(1028);
    public static final int FreeRDP_CompDeskSupportLevel = (int)(3456);
    public static final int FreeRDP_AsyncUpdate = (int)(1545);
    public static final int FreeRDP_RemoteFxImageCodec = (int)(3652);
    public static final int FreeRDP_GatewayUsageMethod = (int)(1984);
    public static final int RNS_UD_16BPP_SUPPORT = (int)0x0002;
    public static final int CS_MCS_MSGCHANNEL = (int)0xC006;
    public static final int RNS_UD_CS_SUPPORT_MONITOR_LAYOUT_PDU = (int)0x0040;
    public static final int FreeRDP_SuppressOutput = (int)(2307);
    public static final int NEG_MULTIDSTBLT_INDEX = (int)0x0F;
    public static final int FreeRDP_PrivateKeyContent = (int)(1417);
    public static final int FreeRDP_Workarea = (int)(1536);
    public static final int FreeRDP_RedirectionAcceptedCert = (int)(1231);
    public static final int FreeRDP_NSCodecAllowSubsampling = (int)(3716);
    public static final int FreeRDP_RedirectHomeDrive = (int)(4289);
    public static final int FreeRDP_RedirectSmartCards = (int)(4416);
    public static final int KEYBOARD_HOOK_REMOTE = (int)1;
    public static final int FreeRDP_instance = (int)(0);
    public static final int FreeRDP_AltSecFrameMarkerSupport = (int)(2434);
    public static final int FreeRDP_AcceptedCert = (int)(27);
    public static final int FreeRDP_BitmapCacheV3CodecId = (int)(3904);
    public static final int FreeRDP_AsyncChannels = (int)(1546);
    public static final int FreeRDP_TcpKeepAliveRetries = (int)(5191);
    public static final int TRANSPORT_TYPE_UDP_FECR = (int)0x00000001;
    public static final int ENCRYPTION_LEVEL_NONE = (int)0x00000000;
    public static final int CHANNEL_OPTION_SHOW_PROTOCOL = (int)0x00200000;
    public static final int FreeRDP_RdpServerRsaKey = (int)(1413);
    public static final int FreeRDP_BitmapCachePersistEnabled = (int)(2500);
    public static final int LOGON_WARNING = (int)0x00000003;
    public static final int FreeRDP_AlternateShell = (int)(640);
    public static final int FreeRDP_KeyboardCodePage = (int)(2623);
    public static final int FreeRDP_KeyboardHook = (int)(2633);
    public static final int TRANSPORT_TYPE_UDP_FECL = (int)0x00000004;
    public static final int FreeRDP_ForceEncryptedCsPdu = (int)(719);
    public static final int FreeRDP_GatewayEnabled = (int)(1992);
    public static final int LB_LOAD_BALANCE_INFO = (int)0x00000002;
    public static final int FreeRDP_DeviceScaleFactor = (int)(149);
    public static final int FreeRDP_DeviceRedirection = (int)(4160);
    public static final int LB_SERVER_TSV_CAPABLE = (int)0x00002000;
    public static final int FreeRDP_WmClass = (int)(1549);
    public static final int LOGON_MSG_BUMP_OPTIONS = (int)0xFFFFFFFB;
    public static final int FreeRDP_Domain = (int)(23);
    public static final int FreeRDP_PromptForCredentials = (int)(1283);
    public static final int NEG_UNUSED23_INDEX = (int)0x17;
    public static final int FreeRDP_TcpKeepAliveDelay = (int)(5192);
    public static final int FreeRDP_AutoAcceptCertificate = (int)(1419);
    public static final int FreeRDP_XPan = (int)(1552);
    public static final int FreeRDP_AllowUnanouncedOrdersFromServer = (int)(2435);
    public static final int FreeRDP_ExternalCertificateManagement = (int)(1415);
    public static final int LB_TARGET_FQDN = (int)0x00000100;
    public static final int FreeRDP_DynamicDSTTimeZoneKeyName = (int)(897);
    public static final int FreeRDP_DesktopWidth = (int)(129);
    public static final int FreeRDP_DumpRemoteFx = (int)(1856);
    public static final int FreeRDP_SurfaceFrameMarkerEnabled = (int)(3522);
    public static final int FreeRDP_KeySpec = (int)(1291);
    public static final int FreeRDP_MouseUseRelativeMove = (int)(1607);
    public static final int FreeRDP_KeyboardSubType = (int)(2626);
    public static final int FreeRDP_HasMonitorAttributes = (int)(397);
    public static final int FreeRDP_ClientBuild = (int)(133);
    public static final int FreeRDP_SpanMonitors = (int)(387);
    public static final int FreeRDP_GatewayUseSameCredentials = (int)(1991);
    public static final int FreeRDP_Password51Length = (int)(1281);
    public static final int FreeRDP_ReaderName = (int)(1293);
    public static final int FreeRDP_RdpKeyFile = (int)(1412);
    public static final int FreeRDP_GlyphCache = (int)(2753);
    public static final int FreeRDP_NSCodecColorLossLevel = (int)(3715);
    public static final int NEG_PATBLT_INDEX = (int)0x01;
    public static final int STATUS_LOADING_DESTINATION = (int)0x00000402;
    public static final int FreeRDP_HasExtendedMouseEvent = (int)(2635);
    public static final int NEG_GLYPH_WLONGEXTTEXTOUT_INDEX = (int)0x1E;
    public static final int FreeRDP_NSCodec = (int)(3712);
    public static final int PERF_FLAG_NONE = (int)0x00000000;
    public static final int FreeRDP_GfxProgressive = (int)(3842);
    public static final int FreeRDP_Username = (int)(21);
    public static final int FreeRDP_TransportDumpFile = (int)(1861);
    public static final int FreeRDP_DisableFullWindowDrag = (int)(963);
    public static final int NEG_MULTI_DRAWNINEGRID_INDEX = (int)0x09;
    public static final int FreeRDP_BitmapCacheV2NumCells = (int)(2501);
    public static final int FreeRDP_PercentScreen = (int)(1538);
    public static final int NEG_ELLIPSE_SC_INDEX = (int)0x19;
    public static final int FreeRDP_CompressionLevel = (int)(721);
    public static final int RNS_UD_15BPP_SUPPORT = (int)0x0004;
    public static final int FreeRDP_RedirectionPasswordLength = (int)(1223);
    public static final int KEYBOARD_HOOK_LOCAL = (int)0;
    public static final int ENCRYPTION_LEVEL_LOW = (int)0x00000001;
    public static final int FreeRDP_MstscCookieMode = (int)(1152);
    public static final int FreeRDP_UseMultimon = (int)(388);
    public static final int RNS_UD_COLOR_24BPP = (int)0xCA04;
    public static final int FreeRDP_ReceivedCapabilities = (int)(2240);
    public static final int FreeRDP_ReceivedCapabilitiesSize = (int)(2241);
    public static final int FreeRDP_RemoteAppNumIconCaches = (int)(2122);
    public static final int FreeRDP_Authentication = (int)(1092);
    public static final int RNS_UD_SAS_DEL = (int)0xAA03;
    public static final int RAIL_LEVEL_LANGUAGE_IME_SYNC_SUPPORTED = (int)0x00000008;
    public static final int FreeRDP_NetworkAutoDetect = (int)(137);
    public static final int FreeRDP_HomePath = (int)(1792);
    public static final int FreeRDP_EarlyCapabilityFlags = (int)(136);
    public static final int REDIRECTED_SESSIONID_FIELD_VALID = (int)0x00000002;
    public static final int FreeRDP_RedirectionTargetNetBiosName = (int)(1225);
    public static final int TSC_PROXY_MODE_DEFAULT = (int)0x3;
    public static final int FreeRDP_FragCache = (int)(2754);
    public static final int FreeRDP_ImeFileName = (int)(2628);
    public static final int FreeRDP_DrawAllowColorSubsampling = (int)(2370);
    public static final int FreeRDP_SupportGeometryTracking = (int)(5186);
    public static final int NEG_MULTIOPAQUERECT_INDEX = (int)0x12;
    public static final int FreeRDP_CurrentPath = (int)(1794);
    public static final int FreeRDP_SupportGraphicsPipeline = (int)(142);
    public static final int FreeRDP_ProxyHostname = (int)(2016);
    public static final int FreeRDP_DynamicChannelArray = (int)(5058);
    public static final int REDIRECTION_VERSION4 = (int)0x03;
    public static final int REDIRECTION_VERSION3 = (int)0x02;
    public static final int MONITOR_PRIMARY = (int)0x00000001;
    public static final int FreeRDP_MonitorCount = (int)(384);
    public static final int REDIRECTION_VERSION2 = (int)0x01;
    public static final int REDIRECTION_VERSION1 = (int)0x00;
    public static final int NEG_LINETO_INDEX = (int)0x08;
    public static final int FreeRDP_StaticChannelCount = (int)(4928);
    public static final int FreeRDP_PrintReconnectCookie = (int)(836);
    public static final int FreeRDP_DrawGdiPlusCacheEnabled = (int)(4033);
    public static final int FreeRDP_GatewayAcceptedCert = (int)(1998);
    public static final int FreeRDP_DrawAllowSkipAlpha = (int)(2371);
    public static final int FreeRDP_SupportVideoOptimized = (int)(5188);
    public static final int FreeRDP_RemoteAssistancePassStub = (int)(1026);
    public static final int FreeRDP_PercentScreenUseHeight = (int)(1557);
    public static final int FreeRDP_NegotiationFlags = (int)(1095);
    public static final int PERF_DISABLE_MENUANIMATIONS = (int)0x00000004;
    public static final int NEG_ELLIPSE_CB_INDEX = (int)0x1A;
    public static final int AUDIO_MODE_NONE = (int)2;
    public static final int FreeRDP_PasswordIsSmartcardPin = (int)(717);
    public static final int FreeRDP_GfxH264 = (int)(3844);
    public static final int AUTO_RECONNECT_VERSION_1 = (int)0x00000001;
    public static final int PERF_ENABLE_FONT_SMOOTHING = (int)0x00000080;
    public static final int FreeRDP_SupportDisplayControl = (int)(5185);
    public static final int LB_TARGET_NETBIOS_NAME = (int)0x00000200;
    public static final int FreeRDP_Pkcs11Module = (int)(1289);
    public static final int PACKET_COMPR_TYPE_64K = (int)0x01;
    public static final int REDIRECTION_VERSION6 = (int)0x05;
    public static final int FreeRDP_UnmapButtons = (int)(1605);
    public static final int REDIRECTION_VERSION5 = (int)0x04;
    /** Pointer to unknown (opaque) type */
    public static class rdpMonitor extends PointerType {
        public rdpMonitor(Pointer address) {
            super(address);
        }
        public rdpMonitor() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class TIME_ZONE_INFORMATION extends PointerType {
        public TIME_ZONE_INFORMATION(Pointer address) {
            super(address);
        }
        public TIME_ZONE_INFORMATION() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class ADDIN_ARGV extends PointerType {
        public ADDIN_ARGV(Pointer address) {
            super(address);
        }
        public ADDIN_ARGV() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpRsaKey extends PointerType {
        public rdpRsaKey(Pointer address) {
            super(address);
        }
        public rdpRsaKey() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class INT32 extends PointerType {
        public INT32(Pointer address) {
            super(address);
        }
        public INT32() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class BITMAP_CACHE_V2_CELL_INFO extends PointerType {
        public BITMAP_CACHE_V2_CELL_INFO(Pointer address) {
            super(address);
        }
        public BITMAP_CACHE_V2_CELL_INFO() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class UINT16 extends PointerType {
        public UINT16(Pointer address) {
            super(address);
        }
        public UINT16() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdpCertificate extends PointerType {
        public rdpCertificate(Pointer address) {
            super(address);
        }
        public rdpCertificate() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class UINT32 extends PointerType {
        public UINT32(Pointer address) {
            super(address);
        }
        public UINT32() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class UINT64 extends PointerType {
        public UINT64(Pointer address) {
            super(address);
        }
        public UINT64() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class GLYPH_CACHE_DEFINITION extends PointerType {
        public GLYPH_CACHE_DEFINITION(Pointer address) {
            super(address);
        }
        public GLYPH_CACHE_DEFINITION() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class ARC_CS_PRIVATE_PACKET extends PointerType {
        public ARC_CS_PRIVATE_PACKET(Pointer address) {
            super(address);
        }
        public ARC_CS_PRIVATE_PACKET() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class ARC_SC_PRIVATE_PACKET extends PointerType {
        public ARC_SC_PRIVATE_PACKET(Pointer address) {
            super(address);
        }
        public ARC_SC_PRIVATE_PACKET() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class rdp_ext_set extends PointerType {
        public rdp_ext_set(Pointer address) {
            super(address);
        }
        public rdp_ext_set() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class CHANNEL_DEF extends PointerType {
        public CHANNEL_DEF(Pointer address) {
            super(address);
        }
        public CHANNEL_DEF() {
            super();
        }
    };
    /** Pointer to unknown (opaque) type */
    public static class RDPDR_DEVICE extends PointerType {
        public RDPDR_DEVICE(Pointer address) {
            super(address);
        }
        public RDPDR_DEVICE() {
            super();
        }
    };
}
